/** @format */

'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
    await queryInterface.bulkInsert(
      'Users',
      [
        {
          name: 'Adi Nugraha',
          username: 'adi_nug',
          password: 'P@ssw0rd1',
          nohp: '081234567890',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Budi Santoso',
          username: 'budi_s',
          password: 'Budi1234',
          nohp: '082345678901',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Citra Dewi',
          username: 'citra_dew',
          password: 'Citra456',
          nohp: '083456789012',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dian Permata',
          username: 'dian_p',
          password: 'Permata789',
          nohp: '084567890123',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Eka Putra',
          username: 'eka_put',
          password: 'Putra567',
          nohp: '085678901234',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Fajar Wijaya',
          username: 'fajar_w',
          password: 'Fajar234',
          nohp: '086789012345',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Gita Amelia',
          username: 'gita_a',
          password: 'Gita5678',
          nohp: '087890123456',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Hadi Kusuma',
          username: 'hadi_k',
          password: 'Hadi987',
          nohp: '088901234567',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Indah Sari',
          username: 'indah_s',
          password: 'Indah123',
          nohp: '089012345678',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Joko Susilo',
          username: 'joko_s',
          password: 'Joko456',
          nohp: '089123456789',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Andi Pratama',
          username: 'andi_p',
          password: 'Andi123!',
          nohp: '081234567890',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rina Sulistiawati',
          username: 'rina_s',
          password: 'Rina456!',
          nohp: '082345678901',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ahmad Rahman',
          username: 'ahmad_r',
          password: 'Ahmad789!',
          nohp: '083456789012',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Siti Aminah',
          username: 'siti_a',
          password: 'Siti123!',
          nohp: '084567890123',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Bambang Kusmawi',
          username: 'bambang_k',
          password: 'Bambang456!',
          nohp: '085678901234',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ratna Dewi',
          username: 'ratna_d',
          password: 'Ratna789!',
          nohp: '086789012345',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Feri Susanto',
          username: 'feri_s',
          password: 'Feri123!',
          nohp: '087890123456',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Linda Rahayu',
          username: 'linda_w',
          password: 'Linda456!',
          nohp: '088901234567',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rudi Setiawan',
          username: 'rudi_s',
          password: 'Rudi789!',
          nohp: '089012345678',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dewi Anggraeni',
          username: 'dewi_a',
          password: 'Dewi123!',
          nohp: '089123456789',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rizky Prasetyo',
          username: 'rizky_p',
          password: 'Rizky123!',
          nohp: '081234567890',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Maya Susanti',
          username: 'maya_s',
          password: 'Maya456!',
          nohp: '082345678901',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Eko Wibowo',
          username: 'eko_w',
          password: 'Eko789!',
          nohp: '083456789012',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Sari Indah',
          username: 'sari_i',
          password: 'Sari123!',
          nohp: '084567890123',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Hendra Santoso',
          username: 'hendra_s',
          password: 'Hendra456!',
          nohp: '085678901234',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Anita Sari',
          username: 'anita_s',
          password: 'Anita789!',
          nohp: '086789012345',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dodi Prasetya',
          username: 'dodi_p',
          password: 'Dodi123!',
          nohp: '087890123456',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Yuli Fitriani',
          username: 'yuli_f',
          password: 'Yuli456!',
          nohp: '088901234567',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Wahyu Setiawan',
          username: 'wahyu_s',
          password: 'Wahyu789!',
          nohp: '089012345678',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Lina Anggraini',
          username: 'lina_a',
          password: 'Lina123!',
          nohp: '089123456789',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dwi Prasetyo',
          username: 'dwi_p',
          password: 'Dwi123!',
          nohp: '081234567890',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rina Puspita',
          username: 'rina_p',
          password: 'Rina456!',
          nohp: '082345678901',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Fajar Wibisono',
          username: 'fajar_w',
          password: 'Fajar789!',
          nohp: '083456789012',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Siti Mulyani',
          username: 'siti_m',
          password: 'Siti123!',
          nohp: '084567890123',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Budi Santoso',
          username: 'budi_s',
          password: 'Budi456!',
          nohp: '085678901234',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Sari Indriani',
          username: 'sari_i',
          password: 'Sari789!',
          nohp: '086789012345',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rizky Pratama',
          username: 'rizky_p',
          password: 'Rizky123!',
          nohp: '087890123456',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Yuli Fitri',
          username: 'yuli_f',
          password: 'Yuli456!',
          nohp: '088901234567',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Wahyu Setiawan',
          username: 'wahyu_s',
          password: 'Wahyu789!',
          nohp: '089012345678',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Lina Anggraini',
          username: 'lina_a',
          password: 'Lina123!',
          nohp: '089123456789',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ahmad Prasetyo',
          username: 'ahmad_p',
          password: 'Ahmad123!',
          nohp: '081234567890',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Siti Rahayu',
          username: 'siti_r',
          password: 'Siti456!',
          nohp: '082345678901',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rizky Wijaya',
          username: 'rizky_w',
          password: 'Rizky789!',
          nohp: '083456789012',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Nurul Hidayah',
          username: 'nurul_h',
          password: 'Nurul123!',
          nohp: '084567890123',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dwi Santoso',
          username: 'dwi_s',
          password: 'Dwi456!',
          nohp: '085678901234',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rini Indah',
          username: 'rini_i',
          password: 'Rini789!',
          nohp: '086789012345',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Surya Pratama',
          username: 'surya_p',
          password: 'Surya123!',
          nohp: '087890123456',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Fitri Yuliana',
          username: 'fitri_y',
          password: 'Fitri456!',
          nohp: '088901234567',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rizal Setiawan',
          username: 'rizal_s',
          password: 'Rizal789!',
          nohp: '089012345678',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Linda Anggraini',
          username: 'linda_a',
          password: 'Linda123!',
          nohp: '089123456789',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Hendra Prasetyo',
          username: 'hendra_p',
          password: 'Hendra123!',
          nohp: '081234567890',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Sari Wijaya',
          username: 'sari_w',
          password: 'Sari456!',
          nohp: '082345678901',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rizki Kurniawan',
          username: 'rizki_k',
          password: 'Rizki789!',
          nohp: '083456789012',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Nina Sari',
          username: 'nina_s',
          password: 'Nina123!',
          nohp: '084567890123',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Fandi Santoso',
          username: 'fandi_s',
          password: 'Fandi456!',
          nohp: '085678901234',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Lina Permata',
          username: 'lina_p',
          password: 'Lina789!',
          nohp: '086789012345',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Surya Prasetya',
          username: 'surya_p',
          password: 'Surya123!',
          nohp: '087890123456',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dini Fitriani',
          username: 'dini_f',
          password: 'Dini456!',
          nohp: '088901234567',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rian Setiawan',
          username: 'rian_s',
          password: 'Rian789!',
          nohp: '089012345678',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Siti Anggraeni',
          username: 'siti_a',
          password: 'Siti123!',
          nohp: '089123456789',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Budi Prasetyo',
          username: 'budi_p',
          password: 'Budi123!',
          nohp: '081234567890',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dewi Wijaya',
          username: 'dewi_w',
          password: 'Dewi456!',
          nohp: '082345678901',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rizal Permana',
          username: 'rizal_p',
          password: 'Rizal789!',
          nohp: '083456789012',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Lina Rahayu',
          username: 'lina_r',
          password: 'Lina123!',
          nohp: '084567890123',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Fajar Santoso',
          username: 'fajar_s',
          password: 'Fajar456!',
          nohp: '085678901234',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Sari Mulyani',
          username: 'sari_m',
          password: 'Sari789!',
          nohp: '086789012345',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rizky Permana',
          username: 'rizky_p',
          password: 'Rizky123!',
          nohp: '087890123456',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Eka Fitriani',
          username: 'eka_f',
          password: 'Eka456!',
          nohp: '088901234567',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Bambang Setiawan',
          username: 'bambang_s',
          password: 'Bambang789!',
          nohp: '089012345678',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rina Anggraini',
          username: 'rina_a',
          password: 'Rina123!',
          nohp: '089123456789',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rahmat Prasetyo',
          username: 'rahmat_p',
          password: 'Rahmat123!',
          nohp: '081234567890',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dina Wijaya',
          username: 'dina_w',
          password: 'Dina456!',
          nohp: '082345678901',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Fauzi Permana',
          username: 'fauzi_p',
          password: 'Fauzi789!',
          nohp: '083456789012',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Linda Nur',
          username: 'linda_r',
          password: 'Linda123!',
          nohp: '084567890123',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Firdaus Santoso',
          username: 'firdaus_s',
          password: 'Firdaus456!',
          nohp: '085678901234',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Sari Susanti',
          username: 'sari_s',
          password: 'Sari789!',
          nohp: '086789012345',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rudi Perdana',
          username: 'rudi_p',
          password: 'Rudi123!',
          nohp: '087890123456',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Eka Fitri',
          username: 'eka_f',
          password: 'Eka456!',
          nohp: '088901234567',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Bambang Setiawan',
          username: 'bambang_s',
          password: 'Bambang789!',
          nohp: '089012345678',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rini Anggraeni',
          username: 'rina_a',
          password: 'Rina123!',
          nohp: '089123456789',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rizky Ahmad',
          username: 'rizky_p',
          password: 'P@ssw0rd1',
          nohp: '081234567890',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dewi Rahayu',
          username: 'dewi_a',
          password: 'Budi1234',
          nohp: '082345678901',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ahmad Santoso',
          username: 'ahmad_s',
          password: 'Citra456',
          nohp: '083456789012',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Sari Fitriani',
          username: 'sari_f',
          password: 'Permata789',
          nohp: '084567890123',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Budi Kurniawan',
          username: 'budi_k',
          password: 'Putra567',
          nohp: '085678901234',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Linda Wijaya',
          username: 'linda_w',
          password: 'Fajar234',
          nohp: '086789012345',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Rina Setiawan',
          username: 'rina_s',
          password: 'Gita5678',
          nohp: '087890123456',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Eka Prasetya',
          username: 'eka_p',
          password: 'Hadi987',
          nohp: '088901234567',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Wahyu Fitri',
          username: 'wahyu_f',
          password: 'Indah123',
          nohp: '089012345678',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Lina Susilo',
          username: 'lina_s',
          password: 'Joko456',
          nohp: '089123456789',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Andi Pratama',
          username: 'andi_p',
          password: 'P@ssw0rd1',
          nohp: '081234567890',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Maya Susanti',
          username: 'maya_s',
          password: 'Budi1234',
          nohp: '082345678901',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Eko Wibowo',
          username: 'eko_w',
          password: 'Citra456',
          nohp: '083456789012',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Sari Indah',
          username: 'sari_i',
          password: 'Permata789',
          nohp: '084567890123',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Bambang Kusumo',
          username: 'bambang_k',
          password: 'Putra567',
          nohp: '085678901234',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ratna Wijaya',
          username: 'ratna_w',
          password: 'Fajar234',
          nohp: '086789012345',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Feri Setiawan',
          username: 'feri_s',
          password: 'Gita5678',
          nohp: '087890123456',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Linda Prasetya',
          username: 'linda_p',
          password: 'Hadi987',
          nohp: '088901234567',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Wahyu Fitriani',
          username: 'wahyu_f',
          password: 'Indah123',
          nohp: '089012345678',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};

